import COLORS from "@/constants/colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1, 
    backgroundColor: COLORS.background,
  },
  startButton: {
    backgroundColor: COLORS.primary,
    marginTop: 20,
    paddingHorizontal: 32,
    padding: 16,
    borderRadius: 12,
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    textAlign: "center",
  },
  startWorkoutContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  startWorkoutTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 16,
  },
  activeWorkoutContainer: {
    paddingLeft: 10,
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  titleContainer: {
    // flex: 1,
    justifyContent: 'center',
  },
  activeWorkoutTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  titleInput: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.textDark,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.textSecondary,
  },
  photoButton: {
    backgroundColor: COLORS.white,
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoButtonText: {
    fontSize: 18,
  },
  timerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    // paddingLeft: 10,
  },
  timerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  },
  exercisesList: {
    marginBottom: 20,
  },
  exerciseItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginBottom: 8,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.textDark,
    marginBottom: 5,
    flex: 1, 
  },
  exerciseDetails: {
    fontSize: 14,
    color: COLORS.placeholderText,
  },
  addExerciseButton: {
    paddingVertical: 12,
    marginRight: 10,
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.blue,
    borderStyle: 'dashed',
  },
  addExerciseText: {
    color: COLORS.blue,
    fontSize: 16,
    fontWeight: '500',
  },
  workoutControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  pauseButton: {
    flex: 1,
    backgroundColor: COLORS.orange,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  resumeButton: {
    flex: 1,
    backgroundColor: COLORS.blue,
    marginLeft: 10,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  controlButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '500',
  },
  endButton: {
    flex: 1,
    backgroundColor: COLORS.green,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.textDark,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingVertical: 80,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 400,
  },
  informationModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingVertical: 80,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  informationModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 300,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    flex: 1,
  },
  headerButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    width: 24,
    height: 24,
    borderRadius: 16,
    borderWidth: 2
  },
  footerButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    width: 48,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
  },
  modalInputBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 16,
    flexDirection: 'row',
  },
  modalInput: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 8,
    fontSize: 16,
    color: COLORS.textDark,
  },
  clearButton: {
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.lightGrey,
    width: 24,
    height: 24,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  cancelButton: {
    flex: 1, 
    backgroundColor: COLORS.background,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: COLORS.textDark,
    fontWeight: '500',
  },
  addButton: {
    flex: 1,
    backgroundColor: COLORS.textSecondary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  addButtonText: {
    color: COLORS.white,
    fontWeight: '500',
    fontSize: 16,
    padding: 10,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: COLORS.textDark,
  },
  resultsSection: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 12,
  },
  exerciseCard: {
    flexDirection: 'column',
    // alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    elevation: 1,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  exerciseInfo: {
    flex: 1,
  },
  selectedExerciseCard: {
    backgroundColor: COLORS.green,
  },
  gif: {
    width: 200,
    height: 200,
  },
  informationHeading: {
    fontSize: 24,
    justifyContent: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  }
})

export default styles